### ISSUE TITLE
Default to selected panels when spectating and you don't own the players selected panels

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-attack#1231]
If you don't have the panels installed of one of the players you spectate, it appears to randomly pick panels.

It would be better if it used the ones you picked.

1. you probably prefer spectating these panels.
2. that way panels aren't changing every game.

**Comment by Endaris** [comment]
Should have been fixed with 1394b2ab8c4c994f2e45dae83579c96ced196fb7
