### ISSUE TITLE
Client disconnects from server if joining a game that's been in progress for too long.

### ISSUE THREAD

**Issue by jon12156** [panel-attack/panel-attack#186]
could perhaps be solved by having a separate thread (coroutine) to fast forward the replay the client gets upon joining the game, 

or, this could be solved by sending the state of the game at a certain frame instead of the replay of the game so far.
games states don't exist yet.  the server doesn't know any game logic, so the game state would need to be retrieved from a player or other spectator. 
This would be a good step towards being able to have better playback of replays too. (rewind, a proper playback bar at the bottom, etc)

**Comment by Omio** [comment]
I wonder if a keyframe system at every 6,000 frames would work, where when catching up, the most recent keyframe is sent from whoever, and the the replay from that keyframe after, meaning that you're catching up to about 100 seconds.

I only worry that creating too many keyframes might impact performance, but too few keyframes makes watching long replays down the road moot.

**Comment by JamesVanBoxtel** [comment]
The processing of messages out of order is also what can cause
https://github.com/panel-attack/panel-attack/issues/227

I wonder if we make sure it holds onto all new message in order and simulates them if that will fix this problem too.

**Comment by JamesVanBoxtel** [comment]
I think this is fixed in the latest beta. We should monitor and close this once it goes in the main build and we don't see any more issues.
