### ISSUE TITLE
Extra panel animation

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-attack#617]
Original discussion: https://discord.com/channels/196674532491132937/854285957347147778/972697157993922590

If panel animation features were to be expanded upon, here's Miz's personal list of frames that should be accessible:

-Landing frames (same as they are now)
-Panic frames (given completely separate frames from the landing frames)
-Two frame flash animation (rather than repeating the neutral frame for half of them)
-4-frame pop animation (see PPL for how this would play out)
-Unique "lose" frame (rather than reusing the pop frame; again, see PPL for example)

-Misc: extending the metal garbage to be 1:1 instead of 1:2? (less of a priority but would be nice) 

This would achieve feature parity with the panels from PPL that we do not have right now!

**Comment by MizunoKetsuban** [comment]
Addendum to this as it expands the system to be more freeform:

Add functionality to the json that allows the creator to define what numbered panel frames are used for which animation, in whatever order is desired. For example, a panel could have an idle animation that uses 1,2,3,4,6,9,1,4,7 if they truly wanted to, just as an example. The full list of animations is as follows:

idle, looping animation
land, non looping animation; does not return to idle until animation is finished or canceled
panic, looping animation
top, looping animation
flash, looping animation
pop, non looping animation; the end of the animation is always lined up with the panel disappearing
next, looping animation
lose, looping animation

**Comment by Endaris** [comment]
Assigned high priority as it is blocking progress on Miz's side.
