### ISSUE TITLE
Implement Title Screen Music

### ISSUE THREAD

**Issue by jankespro12** [panel-attack/panel-attack#903]
Can you implement title screen music in Panel Attack? just like in Original game

**Comment by chickenwaffle** [comment]
> I guess no one is asking me

Apoligies. Things do tend to get buried here 😅

If you want main menu music, provide a main.ogg (or .wav, mp3, etc) in your theme folder.

Some themes implement this, such as Pokémon Puzzle League, Gamecube Panel De Pon, and City Nights.

If you are looking for adding actual title screen music (where the game says "Press Any Key...", then that is an excellent feature suggestion.

**Comment by Endaris** [comment]
Added with #948
